version: 2
jobs:
  build:
    machine: 
        enabled: true
    steps: 
      - checkout

  test:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          command: |
            cd tests
            docker-compose down --v
            docker-compose build
            docker-compose run tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - test